version: 2
jobs:
    build:
        working_directory: ~/react-native-design-patterns
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - node_modules
                  key: v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint
            - run:
                  name: Unit Tests
                  command: |
                      yarn test
